### PR TITLE
 update cmake_minimum_required()

### PR DESCRIPTION
**Pull request by ba7lya**
I failed to compile this project on my computer, the compiler complains ahout serveral lib's cmake version is too low, so i adjust the `cmake_required_version(VERSION 2.8.4)` to `cmake_required_version(VERSION 2.8.4...3.13)`, and it works. hopes it works for somebody else.

### CODE REVIEW

**Comment by tobijk2** [comment]
Im opposed to this change, mainly because the selected cmake version is very new. Concerning the presets: Can you elaborate if the settings can be overwritten freely?  (I could not find a definitive sentence in the cmake docu) Because right now you listed only MS compiler & clib.

Beside that, the main question for me would be, what are the main problems you ran into? Maybe we can fix them without raising the cmake requred version.

**Comment by ba7lya** [comment]
@tobijk2 , thanks for your feedback, check [issue#13](https://github.com/eclipse-basyx/basyx-cpp-sdk/issues/13) pls.

**Comment by ba7lya** [comment]
@tobijk2 update done as your opinion :)

**Comment by tobijk2** [comment]
Thanks, now can you please fill the necessary eclipse contributer agreement and add a Signed-off-by: user@site tag. This is necessary to contribute to an eclipse project. (I didn't notice you hadn't done this already, sorry)

**Comment by ba7lya** [comment]
@tobijk2

- ECA ... done
- "Signed-off-by" ... done

**Pull request merged**
